language: go

go:
  - 1.x

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls

install:
  - glide install -v

script:
  - make build.docker
  - goveralls -v -service=travis-ci
